music_directory     "~/Music"
playlist_directory  "~/.config/mpd/playlists"
db_file             "~/.config/mpd/database"
log_file            "~/.config/mpd/log"
pid_file            "~/.config/mpd/pid"
state_file          "~/.config/mpd/state"
sticker_file        "~/.config/mpd/sticker.sql"
bind_to_address     "localhost"
port                "6600"

audio_output {
    type            "pulse"
    name            "Pulse Output"
    mixer_type      "software"
}

audio_output {
    type "httpd"
    name "HTTP MPD Stream"
    encoder "flac" # or "mp3", "ogg", etc.
    bind_to_address "0.0.0.0" # or a specific IP address
    port "8800"
    compression "0" # for FLAC, 0 means no compression
    bitrate "128" # for MP3/OGG, specify bitrate in kbps
    format "44100:16:2" # sample rate:bits:channels
    tags "yes"
}
