monitor=,highres,auto,1

xwayland {
  force_zero_scaling = true
}

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

env = QT_QPA_PLATFORMTHEME,qt6ct

dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
    smart_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
    disable_splash_rendering = true
    disable_autoreload = true
}

input {
    kb_layout = us,ru
    kb_options = grp:win_space_toggle
    kb_variant =
    kb_model =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}


ecosystem {
    no_donation_nag = 1
    no_update_news = 1
}

