background_opacity 0.8

font_family 0xProto Nerd Font
font_size 14.0

paste_actions quote-urls-at-prompt

strip_trailing_spaces never

select_by_word_characters @-./_~?&=%+#

term xterm-256color

disable_ligatures always

dynamic_background_opacity true

shell_integration enabled

