source = ~/.config/hypr/conf.d/profile-pre.conf

source = ~/.config/hypr/conf.d/programs.conf
source = ~/.config/hypr/conf.d/general.conf
source = ~/.config/hypr/conf.d/binds.conf
source = ~/.config/hypr/conf.d/autostart.conf

source = ~/.config/hypr/conf.d/profile.conf

